# Generated by Django 5.2.6 on 2025-10-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0002_alter_purchase_fees_alter_purchase_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_banned',
            field=models.BooleanField(default=False, help_text='Whether this customer is banned from renting or purchasing'),
        ),
    ]
