# Generated by Django 5.2.6 on 2025-10-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0003_customer_is_banned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='default_price',
            field=models.DecimalField(decimal_places=2, help_text='Default price used if rent/sale prices not set', max_digits=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='rent_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per day', max_digits=25, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='taxes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='trade_in_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name='rental',
            name='manual_late_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Manually set late fee amount', max_digits=25),
        ),
    ]
