# Generated by Django 5.0.14 on 2026-04-15 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0005_alter_customer_email_alter_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='trade_in',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='trade_in_value',
        ),
    ]
